### ISSUE TITLE
open local file

### ISSUE THREAD

**Issue by def00111** [zoehneto/chrome-rtf-viewer#3]
Maybe you can do something like these add-ons do?
https://github.com/ssborbis/ContextSearch-web-ext/blob/native-app-support/options.js
https://addons.mozilla.org/firefox/addon/stormfiles/

**Comment by zoehneto** [comment]
Something similar could certainly be added in the future, though it has the drawback that you have to select the file to open from the browser extension instead of opening it straight from your file manager. I'd certainly be open for PRs but it's not a priority for me since it works in chrome where the majority of the users are.

**Comment by alterechtschreibung** [comment]
yes, this would be great

**Comment by zoehneto** [comment]
I have added this feature with version 1.3.1. It is already published on addons.mozilla.org, the chrome version should be available within the next hour.

**Comment by alterechtschreibung** [comment]
Thank you.
